### ISSUE TITLE
3.2 Update

### ISSUE THREAD

**Issue by Leinad4Mind** [ForumHulp/Copy_Lang#1]
Could this be updated to work on 3.2?

Thanks!

**Comment by ForumHulp** [comment]
Will you test it, Clear cache by hand as acp templates aren't purched in a good way.

**Comment by Leinad4Mind** [comment]
Great! Thanks for the update!

2 Little Problems:
ADD_FILE language variable
After uploading a zip file it appears a page with text, we need to refresh to see the acp again.
> "en":{"iso":"en","name":"British English","local_name":"British English","author":"phpBB Limited"}

1 Big Problem:
After selecting 1 language to go to another, it will create a zip file. That zip file with the update language is corrupt 0kb.

**Comment by ForumHulp** [comment]
You was right, I only checked the zip file on the server and not the download. It should be ok with this update now. 
Clear your cache as it should lad plupload.
